### ISSUE TITLE
Explode setting keys but not moving objects

### ISSUE THREAD

**Issue by jcdied4me** [franMarz/TexTools-Blender#155]
I have a set of separate meshes (labeled with low and high) that are a part of the same object. The low and high are on top of one another. I select all objects in the set, both low and high, the explode option becomes available, then I press the button. It adds a position keyframe for all assets at both zero and 50 like it should. But no change in position for any object. I have tried this in 3.2 and 3.4 with no good results.

**Comment by franMarz** [comment]
Yes, is not working correctly in 3.3 either.
Anyway, as I said in previous issues for your use case: "Explode" moves each baking set/group/pair apart from one another, only if you have multiple baking sets selected. This means you should get a "Bake >1x" text message in the Bake button (with bake single uncheked) for Explode to work. Separating high and low pairs is not implemented neither planned to be.
We have to fix it to recover that expected behaviour in any case.

**Comment by jcdied4me** [comment]
Above represents what I tried, yet nothing works. I tried separate names, I tried naming in a series (.001 .002 .003, etc.) with appended high and low, and with high and low before the series numbers, and I tried parenting but nothing is working. Below are screenshots of each attempt.

Is the below image what you say you are not planning to implement?
![ExplodeBefore](https://user-images.githubusercontent.com/7097167/206870940-6a7527c8-7606-4698-a369-760e80b25619.PNG)

All objects named uniquely with high and low appended, but they are parented under a single object with high or low appended to its name. Shows up as one object in the bake panel and Explode button disabled. 
![ExplodeBefore 002](https://user-images.githubusercontent.com/7097167/206872029-cf4faf65-da94-40be-a779-e2c3771be00b.PNG)

Series number appended to the name of the object then high and low appended. Shows separate objects, explode button available, and bake number represents the amount of object sets selected. Still no explode.
![ExplodeBefore 003](https://user-images.githubusercontent.com/7097167/206872031-a8382837-7cc2-43fd-a4c9-fd3b2a80d160.PNG)

Names same, series number appended to end of high or low designation. Shows up as one object in the bake panel and explode is not visible, and bake button 1x.
![ExplodeBefore 004](https://user-images.githubusercontent.com/7097167/206872312-550a738f-331e-46a7-b036-9492fb1f5777.PNG)

Also:
I am still not quite sure what you are referring to by set/group/pair. Let me try to define these terms as they do not exist in Blender. 
**Set:** as described in the documentation is a series where they share a name with high and low appended, then suffixed with .001, .002, .003, etc..
**Group:** Main object named with high or low suffix, and parent all subsequent objects to this main object (my understanding is that any of the child objects do not need to have high or low appended nor do they need the name to be in series?)
**Pair:** Two objects only, with the same name. Append high and low. 

Any help resolving this issue would be much appreciated.

**Comment by franMarz** [comment]
A set is a group of objects that bake together. The default behaviour of the addon is grouping objects by their base name, as you describe. Objects forming pairs, sharing the same base name and adding the lo or low and hi or high suffixes bake in a single texture also. All these objects form groups named sets, or bsets, internally in the addon, and all objects inside a set move the same amount respect other objects of other sets, so that rule of thumb of having that "Bake >1x" text message in the Bake button is all you need to have for Explode to really work.
But as I said, even in that situation the utility is not working properly, I don't know when and why this stopped working, but I've been reviewing the code and it's full of things to improve. I don't even know how this worked previously.
I'm not the author of this addon but I've been working on most of its modules, but now I don't have much time. I don't have much interest in this Explode utility neither, to be honest.
Anyway, I'll upload some improvements to the code quite soon, but I'm not refactoring it as much as it is needed.

**Comment by franMarz** [comment]
Please try the [latest version of master](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip) and tell me if it works for you now.

**Comment by jcdied4me** [comment]
It worked! With and without selecting the single texture checkbox.

![ExplodeWorking](https://user-images.githubusercontent.com/7097167/206883218-50020949-8100-4884-9283-94dae76711ad.PNG)

Are there any known bugs with the master version? Will this release as a standard version soon? I ask because I am creating tutorial content and want to make sure those who I teach this to has access to a working version. 

Thank you!

**Comment by franMarz** [comment]
Nice!
I have to test Master with the latest version of Blender, 3.4. With 3.3 is working properly, some issues with edge selections but not really bugs, as far as I can tell.
We don't usually make releases until a bunch of enhancements are accumulated, so you better use and recommend using Master.
Thank you for the report and for spreading the word about TexTools.

**Comment by jcdied4me** [comment]
Can I link the master Textools you sent me? Or is that only temporary?

BTW: the version I tested it on is 3.4. Been using it to create tutorials for the last few hours without issue. Maybe a bit of a  lag when rendering normal maps at 2048x2048. But nothing too drastic. Thanks for the assist. Super happy with explode. I knew it couldn't be that complicated.

**Comment by franMarz** [comment]
That link is not temporary, always refers to the latest version of master, so you can use it.

Ok that is cool, than you for sharing. I have to test all utilities in 3.4 myself anyway.

It took me like 5 hours to fix this, in a hacky way. Not as easy as it seems. Refactoring the code would be needed, it's too complex for what it does. But it works now, so it's something.

**Comment by jcdied4me** [comment]
I appreciate you spending time to hack the feature together. It works great! Looking forward to seeing it in a release. 

PS: Are you planning on adding a UV packing feature to the tool? It would be nice to have one addon to deal with all UV needs.

**Comment by franMarz** [comment]
For packing I personally use [UV Packer](https://blenderartists.org/t/uv-packer-for-blender-free-windows-macos/1287541), the best free UV packing utility I know. It has an external application and the python module works as a bridge, it's not entirely open source, so I can't add it to our package.
Coding a packer ourselves is out of the question, just too complicated and slow if we do it in Python.

**Comment by jcdied4me** [comment]
Fair enough. I use UV Packer as well. Great free addon. Thanks again for the help with the explode feature.
