### ISSUE TITLE
Align World fails.

### ISSUE THREAD

**Issue by cantcodetho** [franMarz/TexTools-Blender#161]
Align World fails on something as basic as cylinder with removed top and bottom faces and a single front seam. So that is basically rectangular strip of polygons in UV editor. When using Align World it rotates these UVs to 45 or so degrees which is incorrect.

**Comment by franMarz** [comment]
Certain topologies fail, yes. A cylinder seems to be simple, but it isn't.
I think it's worth trying to only align faces whose edges are all not marked as seams, or which have the less amount of seams if the previous method is not possible due to all faces having seams.
Or maybe it's worth checking how it was implemented in Blender.

**Comment by franMarz** [comment]
The latest improvements from commits f8b321fbe6e98ac91bc18ac18a38d8ece54c3af1 and 20f583a9e26c83dea9a314eb0bd52b860abbadd4 should be enough to handle any scenario; I can't see now a more automated approach. Closing
