### ISSUE TITLE
This is a suggestion for enhancing the "overlap" request feature.

### ISSUE THREAD

**Issue by sangouzhi** [franMarz/TexTools-Blender#170]
![3](https://github.com/SavMartin/TexTools-Blender/assets/114461992/49aa6af5-96ba-4dc8-adae-c405a82c17db)
![1](https://github.com/SavMartin/TexTools-Blender/assets/114461992/7f9c44aa-5e8e-4fdd-a188-49083d138a25)
![2](https://github.com/SavMartin/TexTools-Blender/assets/114461992/6db26998-b0cc-476c-a42d-46baa9820e38)
The general idea of these images is that after we have arranged the UVs, I want the pixel distance between each UV to be consistent. For example, it could be 4, 6, or 8, as shown in the figure above. When the distance between adjacent UVs is less than the specified value, it will be considered as an "overlap

**Comment by sangouzhi** [comment]
This feature is very useful and commonly used in 3D game art UV production, but for some reason, no one seems willing to develop it. I've suggested this to many software developers, but they haven't responded. I don't understand why, as most game art developers encounter this problem. It's a necessary feature, and Blender doesn't have it

**Comment by sangouzhi** [comment]
If you have any questions, feel free to ask me. I hope to see this feature in the text tool soon. Thank you.

**Comment by franMarz** [comment]
We use the bpy.ops.uv.select_overlap operator from the Blender API to detect overlapping uv faces, and it hasn't got this capability. Coding this ourselves, in Python, would be too slow because of it running only in one thread when working with Blender data, and the calculations are fairly complex and heavy for dense meshes.
It would be a nice feature to have, but is too complext to code (in another language, using this addon as a bridge) and thus out of the scope of TexTools.
Thank you anyway.
