### ISSUE TITLE
Overlap tool doesn't always work with mirrored UV islands

### ISSUE THREAD

**Issue by Telefragg** [franMarz/TexTools-Blender#180]
Currently Overlap tool doesn't work properly with stacked islands that were created by applying the Mirror modifier on the mesh. I haven't been able to replicate the problem, but generally in 9/10 times Overlap selects the whole stack of islands, without leaving 1 island unselected like it is supposed to do. Islands stacked manually by merging verticies are selected like intended more often, but still sometimes the whole stack is picked up. MagicUV addon selects mirrored islands properly always (but sometimes crashes while doing so). This is a super useful feature for baking symmetrical meshes, I hope someone will be able to look into it.

**Comment by franMarz** [comment]
Since TexTools 1.4.0, Overlap uses the builtin Select Overlap operator (bpy.ops.uv.select_overlap), extends the selection to the whole islands with bpy.ops.uv.select_linked, and deselects only 1 random island among all selected islands (not 1 for each stack of overlapping islands) using a custom function. I explained it just in case. If this fails in certains situations, I don't see a fast method to improve it, because a custom overlap calculation using the Python API would be very slow and may fail in some more common scenarios.

Anyway, I'll let this open for the time being, maybe someone can look into it.

**Comment by deepdeliberate** [comment]
My guess is, the UVs you have in your source meshes, sometimes have middle vertices connected to the mirrored part. I have experienced this kind of UV problem regardless of the addon, I think I would prefer you use UV offset of mirror/array modifier to avoid stacking of the UV if mirror ones are causing issue.
There is one more workaround, disable the merge vertices in mirror modifier and then apply it and then just manually remove doubles by selecting the middle section, that result in stack of UV but both pieces will be unjoined, and works with the Textools addon as expected

**Comment by franMarz** [comment]
What @deepdesperate says would be of help to the end user. We can also change the island discovery function and hopefully solve the problem altogether.

**Comment by franMarz** [comment]
This should be solved thanks to recent changes in master. Closing.
