### ISSUE TITLE
Issue with "Straight" feature under "UV Layout".

### ISSUE THREAD

**Issue by kushag09** [franMarz/TexTools-Blender#204]
Trying to straighten the edge of my UV but apparently it doesn't do anything. Attached a video here showing the issue, please check. Using Blender 4.0 and TexTools version 1.6.1.

https://github.com/franMarz/TexTools-Blender/assets/67006397/cdd3427a-0fb4-43bc-b203-b5d433c32662

**Comment by franMarz** [comment]
Could you please share a simplified file containing the geometry of that problematic UV island only?

**Comment by kushag09** [comment]
Sure, here's the obj file - https://drive.google.com/file/d/18EXeTFQR3sEntTliTZRohthk7hRhQSHF/view?usp=sharing

Couldn't share it via github as it isn't supported.

**Comment by kushag09** [comment]
Hi,
I reinstalled the textools with the changes you made, the feature still doesn't seem to work for me. Is it because of the geometry?

https://github.com/franMarz/TexTools-Blender/assets/67006397/e6658046-d0aa-4c2e-aecd-127b060ba93b

I noticed one thing, if I make changes to the uv like scaling, rotating and then perform the "straight" feature, it reverts all these changes made.

**Comment by franMarz** [comment]
Straight worked for me even before my last commit. I thought that the problem should be bound to the object being active but not selected in your blendfile, because you sent me the OBJ file and I selected the object and it worked. Please send me a simplified version of the blendfile, only with that shirt piece, zipped. You will be able to upload the ZIP archive here.

**Comment by kushag09** [comment]
[Shf.zip](https://github.com/franMarz/TexTools-Blender/files/14834673/Shf.zip)

Here's the zip file. I am using blender 4.0, maybe it could be the issue of the blender version.

**Comment by franMarz** [comment]
I use the same version. The problem is that you have Live Unwrapping enabled. Just deactivate Live Unwrap while in Edit Mode from the Options popover at the top right corner of the 3D Space Editor. This should be exposed more clearly in the Blender UI tbh. We have to consider whether TexTools should alert about this, like it used to do with UV Selection Sync when most of the tools were not compatible with it.
