### ISSUE TITLE
"Select Bounds" only works in UV sync selection mode

### ISSUE THREAD

**Issue by Fak3** [franMarz/TexTools-Blender#21]
When Select Bounds is clicked, the UV editor force-switches off "UV sync selection" mode, bounds are selected in the 3d viewport and everything in the UV editor gets deselected. Only if you manually enable sync mode on in the UV editor, you can see that bounds are indeed selected.

Expected behavior: When Select Bounds is clicked, then bounds should be selected in the UV editor, regardless of the "UV sync selection" mode.

**Comment by franMarz** [comment]
The script doesn't even work as intended if your mesh is non-manifold. It uses the UV operator "Seams From Islands" to find the island bounds, the problem is that it doesn't mark seams on boundary edges, but on edges shared with other faces only. This makes the Select Bounds to fail in the first place in most cases.
Moreover, Select Bounds operates on all the islands, not in the selected one only. This seems to be the intended behaviour, but honestly, I don't see the point of selecting the bounds of all the islands. See #8 .
Recovering the state of UV Selection Sync is possible and fairly easy to code, but it won't make this function to work properly. It should be reviewed entirely.

**Comment by franMarz** [comment]
We better forget the idea of this working without sync, unless UV editing evolves so edges become cleanly selectable. It's impossible now with the current system based on loops. I'm making a pull request to have this working as better as possible with and without sync, but in cases where interior edges share both its vertices with boundary edges, they will be selected.
