### ISSUE TITLE
Tool 'builtin.select_box' not found for space 'VIEW_3D'

### ISSUE THREAD

**Issue by TheZokman** [franMarz/TexTools-Blender#215]
Upgrading to blender 4.0+ seems to have pickled the ability to bake Color ID, from Material to Vertex Color. No info about it online so I am assuming it's an issue since it has worked before.

**Comment by franMarz** [comment]
I don't know whether I'm understanding your issue fully, the ticked title doesn't help. But I think your problem is bound to the following:

1. If you're in the Materials mode of Color ID, you have to use the Base Color or Diffuse baking modes to render the result of the Color ID assignation, not the Material ID baking mode.
2. If you're in the Vertex Colors mode of Color ID, you must know that we don't have a "Color attribute" or "Attribute" baking mode yet. If any baking mode worked for you before as a way of baking Vertex Colors, it was because a bug.

**Comment by TheZokman** [comment]
I believe you're right, it must have been a bug with an earlier version of
the addon / blender. I got it working now after trying different settings

**Comment by franMarz** [comment]
Ok, closing this.
