### ISSUE TITLE
Not assigning checkermap materials automatically

### ISSUE THREAD

**Issue by Tufis16** [franMarz/TexTools-Blender#220]
I have a question. Normally when i click to the "checkermap" button, automatically adding that object for example "TT_checker_512x512_UV_GRID" material and assigns it. But now, it did not happening. I really need help why? 

Example video: [https://drive.google.com/file/d/14sFkkxnDmGH0X8f9OILRmtf-GEBasBN1/view?usp=sharing](javascript:void(0);)

Using Blender 4.0.2 (sometimes work), Blender 4.2 (need to work in this)

**Comment by franMarz** [comment]
It is added now as a Geometry Nodes Modifier working as a material override per object, since 2c5d574. Read the description of the commit to find out the reason of the change.
Checker materials are internally cleared after a cycle (when you recover the original materials on all objects, after clicking in the Checker Map button 4 times). If you need them actually assigned, you'll have to do it manually or with a dedicated script.
Closing.
