### ISSUE TITLE
Checker Issues 1.6.1 Blender 3.6.14

### ISSUE THREAD

**Issue by markesmith** [franMarz/TexTools-Blender#222]
Hi,

I'm seeing issues with the checker texture feature in TT 1.6.1 and 1.6 having just rolled back. I'm currently using blender 3.6.14. 

First issue is the checker button only ever creates 512x512 textures regardless of the map size chosen in the size dropdown menu. 

Second issue is I can easily break the creation of the 3 types of map by simply creating the checker maps in a fresh scene, cycling through the 3 maps types and then removing the maps by using the trash can button + alt to remove from the blender scene. 

Thanks for maintaining the addon. If you require any further info please ask. 

MES

**Comment by franMarz** [comment]
That was an intentional change, we envision checker maps as temporary textures only created for in-viewport visualization of UVs distortion on objects. Previous behavious was very bad, as it was destructive towards textures and materials already present in the objects, replacing them; now we use material overrides by using a geometry nodes modifier with the checker maps created and destructed internally without affecting other data already present in the Blendfile.
If you need Checker Textures of different resolution, you'll find the option to create them within the Image Texture nodes of the Shader Editor. This addon is not for accelerating the creation of checker textures, we just use them as helpers.

If you still don't share our vision, please visit already tackled issues #216 and #220 to better understand the changes.
Closing.
