### ISSUE TITLE
Cannot create checker map larger than 512 in blender 4.2

### ISSUE THREAD

**Issue by wirelessfuture** [franMarz/TexTools-Blender#230]
Title basically. Doesn't matter if we choose preset size or enter the size manually, it always comes out as 512.

**Comment by franMarz** [comment]
This issue have arised a number of times now, this is strange to say the least. I think I know where this comes from. Anyway, I'll explain this again. This addon is not for creating Checker Maps, I changed the behaviour of the Checker operator so it's only bound to UV flow visualization in viewport, so since 2c5d57471a29f1d42cf45068f7407fc26f7fc7df the maps are just linked from the Resources folder at a fixed 512px resolution, enough for in viewport visualization, while the scale of them can be adjusted per object since 12e501accefe61ce14401d428dfb202cd6b3674d. This won't change as many problems were solved with the refactor, please read the commits.
