### ISSUE TITLE
Baking doesnt work in Blender 4.3

### ISSUE THREAD

**Issue by skisys** [franMarz/TexTools-Blender#246]
Hello!

I did an Blender update, but now Textools isnt working anymore. I want to bake an ID Map but it doesnt want to bake my colors. Any other baking option also brings me to the same error. It only outputs a blank, black image. This is the error:

Python: Traceback (most recent call last):
  File "C:\Users\luthe\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\TexTools-Blender-master\op_bake.py", line 493, in bake
    assign_tune_materials(obj, setup_bake_nodes=True)
  File "C:\Users\luthe\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\TexTools-Blender-master\op_bake.py", line 408, in assign_tune_materials
    modes[mode].setVColor(obj, previous_materials)
  File "C:\Users\luthe\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\TexTools-Blender-master\utilities_bake.py", line 445, in setup_vertex_color_id_material
    bpy.ops.paint.vertex_color_set()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.3\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.paint.vertex_color_set.poll() failed, context is incorrect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\luthe\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\TexTools-Blender-master\op_bake.py", line 676, in bake
    bpy.ops.object.select_all(action='DESELECT')
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.3\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.object.select_all.poll() failed, context is incorrect

**Comment by franMarz** [comment]
I can't reproduce this issue. Could you please share with us a simplified example file where this happens?

**Comment by justindesilets** [comment]
I can confirm I'm seeing the same issue. I was able to repeat the issue by doing the following.

1. Launch Blender 4.3.0
2. Go to General and leave the default cube
3. Select UV Editing from the top
4. Expand the TexTools menu from the left UV Editor screen
5. Click Color ID in the TexTools menu
6. Change Color ID mode from Materials to Vertex Colors
7. In the right side 3D viewport, switch to edit mode
8. Select a single face
9. In the TexTool menu, clicking on any color to assign it to face triggers the error
10. I noticed that in the 3D viewport the mode switches from edit mode over to Vertex Paint mode at the same time this error occurs.

Please see the below screenshot for more details. To me, it seems like this issue is caused with trying to use the Vertex Color mode. If you use Material mode for the Color ID, this error does not occur. I can assign individual colors under material mode, and the TexTool utility works as expected.
![image](https://github.com/user-attachments/assets/bdcd7e34-7d68-4349-a6b9-4abf642f84c1)

**Comment by franMarz** [comment]
@skisys I was trying Element ID, not Material ID. I can reproduce and fix it now.
@justindesilets This was working before for some reason, but it's no longer the case. Thanks to your post, now it's fixed in all affected tools.

**Comment by justindesilets** [comment]
Thank you @franMarz for maintaining such a helpful plugin. I know the community really appreciates it.

**Comment by skisys** [comment]
Thanks a lot for your help! It works again :)
