### ISSUE TITLE
Bug with Material ID Bake mode - 2.91

### ISSUE THREAD

**Issue by JustSaiyan01** [franMarz/TexTools-Blender#30]
Have noticed a bug with the Material ID mode where the colours are not corresponding to the correct faces that they were assigned to. When using Diffuse mode the colours are correctly assigned though.

![mat id bug](https://user-images.githubusercontent.com/55152007/89430281-7e932600-d736-11ea-89ba-8d451be7744b.png)
![mat id bug 2](https://user-images.githubusercontent.com/55152007/89430298-8357da00-d736-11ea-8dc1-39b839703904.png)

Here is diffuse mode as well.
![diffuse id](https://user-images.githubusercontent.com/55152007/89430338-8eab0580-d736-11ea-930d-7d256f424020.png)

**Comment by adrieOlie** [comment]
I am also having the same problem. I thought it was left over data when I first baked the material ID but this is on a previous version which hadn't been baked on. (I am using Blender 2.83.2)
![image](https://user-images.githubusercontent.com/44616307/92018576-ef6c3480-ed1a-11ea-92e8-4416762db154.png)

**Comment by SavMartin** [comment]
Are you working with a AMD graphics card?

**Comment by JustSaiyan01** [comment]
Yeah I have a AMD GPU, specifically a Vega 56 and I'm on driver version 20.7.2.

**Comment by SavMartin** [comment]
Ít a Blender bug , try download last drivers of graphics card..

**Comment by Losco-Nosciuto** [comment]
I am having the same issue on an RTX2080S @SavMartin 
![image](https://user-images.githubusercontent.com/35420766/98110639-ae6dd900-1e9f-11eb-8aec-65eebe678413.png)

I thought it was some weird blend mode between residual material colors and the new ones but happens in the new model too :(

**Comment by Losco-Nosciuto** [comment]
Just to be sure I tried on a friend of mine's PC, who has no AMD parts at all, it's all NVidia and Intel. He tried both on a current gen PC and a Past-Gen PC.
The result is the same. 
The colors gets randomly mixed without any apparent sense. Mostly it seems to use purples in different scales, yellows are a rarity without photoshop. Idk what criteria this bug happens on, but it has nothing to do with AMD, both GPUs or CPUs.

Hoping to be of any help

**Comment by JustSaiyan01** [comment]
Been a while since I've also gave an update. Just came to mention that this still happens even on the latest AMD drivers 20.11.1 ; this even happened on driver version 20.9.2. As others are now reporting this happens on Nvidia cards, maybe it's not a driver issue.

**Comment by Losco-Nosciuto** [comment]
Nah, It's abandonware.

better go look for an alternative or rely on vanilla blender tools for UVW and baking at this time.

Also the unresearched "It's a Blender bug, update graphics card drivers" along with "it's due to AMD stuff" isn't convincing at all.

That's bad because I loved the 3DS Max version of it

**Comment by franMarz** [comment]
Material ID assigns a unique, distinguishable color to each uv face based on its material ID (_material slot_ order) for every object on the bake, [this is the designed behaviour](http://renderhjs.net/textools/blender/), and the way this type of mask generation works in other packages across the industry. I'm going to change it, so that the unique color is linked to the material name, not the material slot, for the result to be more predictable when baking multiple objects. Maybe this is not the desired outcome for all the users though, we'll see.
The color is going to be random still after the patch. If you want that color to match the diffuse color, just use diffuse baking.
