### ISSUE TITLE
[Feature Request] Add the ability to bake standard PBR maps.

### ISSUE THREAD

**Issue by Igrium** [franMarz/TexTools-Blender#41]
The texture baking feature of TexTools is really useful, and I find myself using it every time I do material work in Blender. I still find it annoying, though, to use Blender's native baking tools when baking down my final PBR maps, so it would be nice if Roughness and Emit (and Metalness if that's possible) were present in the list of baking modes.

**Comment by feilen** [comment]
https://github.com/SavMartin/TexTools-Blender/pull/43 I have roughness taken care of (well, mostly, needs a new icon) and smoothness if you're using Unity. Metallic will require Blender to support it, which is something I might try to tackle sooner or later.

**Comment by SavMartin** [comment]
Already included, thx to @feilen ... great work

**Comment by franMarz** [comment]
Maybe this could be closed then?

**Comment by Ulazygit** [comment]
There is still no option to bake metallic and emission maps using this plugin. I downloaded the latest release? Kind of pointless without metalness and also without emission. Shame because the plugin is much easier to use than alternative.

P.S. I think a metallic workaround could be programming a switching of metallic and roughness then baking a roughness (actually metallic)

**Comment by feilen** [comment]
I've actually been working on that for another plugin, it might be possible to backport them here (if licensing isn't an issue)

So far I've got metallic, alpha, emit working fine (most of the time, some rare issues in alpha)

**Comment by feilen** [comment]
@SavMartin any concerns about the licensing? This project is GPLv3, the project I've been spending more of my time on ([cats blender plugin, specifically this PR](https://github.com/GiveMeAllYourCats/cats-blender-plugin/pull/221)) is MIT. It shouldn't be an issue since I wrote the other changes from scratch and I'd have to rewrite most of it to work here, but ultimately it's your decision, since yours has the less permissive license and there's bound to be one or two duplicated lines.

**Comment by franMarz** [comment]
Where could be any issue? You're copying two lines from a code under MIT, that's fully permissive, to GPLv3, that is also very permissive, but not even from here to MIT, so... I personally say, please, bring us that new functionality.

**Comment by franMarz** [comment]
Added the remaining PBR bake modes in TexTools 1.4.1, download and install the latest release: [https://github.com/SavMartin/TexTools-Blender/releases/download/v1.4.1/TexTools_Blender_1_4_1.zip](https://github.com/SavMartin/TexTools-Blender/releases/download/v1.4.1/TexTools_Blender_1_4_1.zip)
