### ISSUE TITLE
Baking ineffective at very high poly counts

### ISSUE THREAD

**Issue by CJYen** [franMarz/TexTools-Blender#48]
This Addon is my favorite, too

I noticed during baking highpoly to lowpoly, at very high poly meshes (+80.000 verts)
The Addon baker gets stuck in astronomical times for baking, while the blender cycles internal took 20s for the exact same.

The inner text comes from
https://bitbucket.org/renderhjs/textools-blender/issues/3/baking-ineffective-at-very-high-poly

**Comment by AvisParadocs** [comment]
It happens because of material restore on highpoly mesh after bake process is finished. To solve that freeze you need to disable face indexing by commenting lines from 157 to 159 in utilities_bake.py. It works for me. Hope it will help someone one make a proper fix for textools in future.
![1a4b94707d96400d007ac557a30e9aca10afb49e](https://user-images.githubusercontent.com/41724684/99712855-aa070a00-2ab4-11eb-98f1-48cf790c0b08.jpeg)

**Comment by franMarz** [comment]
I'll investigate whether is it possible to deactivate the store/restore of materials in certain bake modes for speeding up the process.

**Comment by franMarz** [comment]
More or less fixed on my side, but I think there is still more room for improvement using object duplicates instead of the store/restore functions, I'll try to rewrite the code in some extent before committing what I already have.

**Comment by franMarz** [comment]
Fixed in TexTools 1.4.1, download and install the latest release: [https://github.com/SavMartin/TexTools-Blender/releases/download/v1.4.1/TexTools_Blender_1_4_1.zip](https://github.com/SavMartin/TexTools-Blender/releases/download/v1.4.1/TexTools_Blender_1_4_1.zip)
