### ISSUE TITLE
Blender shuts down without warning while baking texture 8192

### ISSUE THREAD

**Issue by End782** [franMarz/TexTools-Blender#71]
I tried to bake a Bevel Normal map for 8192 but Blender was flashing away without warning.
I had to bake 4 4096 texture to put them together.
This is a bit troublesome, can you add this function?

**Comment by franMarz** [comment]
Not the first time I see a report like this, and the last one was related to exceeding the memory limits (physical and virtual) of the user's computer. The issue could have been worsened if AA is used (2x renders a 16k texture, and 4x a 32k texture for 8096), and if the GPU is used for rendering, as it usually has a much less memory cap than the CPU.
Maybe Bevel Normal has room for improvement though, as it is a custom method.
So please try a bake of a plain Normal using both TexTools and the usual baking workflow in Blender to help us find out whether or not this issue is related to Textools or the Bevel Normal baking mode.

**Comment by End782** [comment]
Use TexTools Tangent Normal 4XAA 8192 Blender to close
Use Usual Bake(GPU) 8192 1024 Sampling Blender to run well
Use Usual Bake(GPU) 32768(4x8192) 32 Sampling Blender to close
It seems that when the computer's memory is completely used, Blender shuts down

**Comment by franMarz** [comment]
I can only give you the advice of using CPU and increasing your system virtual memory limit if you're going to render at such a high resolution.
I'm closing the issue as it is not related to TexTools.
