### ISSUE TITLE
Fill and Crop

### ISSUE THREAD

**Issue by Oxicid** [franMarz/TexTools-Blender#74]
In your version 1.4.0, the Fill function works like Crop. While in 1.3.0 everything is fine, except that the UV is randomly rotated.
![1 3 0](https://user-images.githubusercontent.com/76912541/112156851-aff23080-8bf7-11eb-96cb-664baf7393cc.gif)
![1 4 0](https://user-images.githubusercontent.com/76912541/112156854-b08ac700-8bf7-11eb-8f81-10d7a1f4de58.gif)

**Comment by franMarz** [comment]
In 1.4, Fill scales and rotates the islands to use the maximum uv space without distortion. Crop does the same but without rotation, so that in most cases the result is the same. This was changed while adding the multi-object uv editing support, if I remember it correctly, probably because of some limitations of that implementation. I see this as a feature, some may consider that this is a bug, but I consider a top priority to avoid absolute or relative distortion of uvs as much as possible (for example, Random Scale was not added because of this although it would be really easy to add)

**Comment by onlinefrog** [comment]
Bummer! fill was one of my most used operators, as I often need to perfectly stretch uvs to square bounds. Why secretly change the core behavior instead of adding a 'preserve aspect' option? I ported the code from the c0672e3 release for my own use and it works fine, though not compatible with multi-object editing of course : ^ )

**Comment by franMarz** [comment]
Solved in the latest version of master: [https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip](https://github.com/SavMartin/TexTools-Blender/archive/refs/heads/master.zip)
