### ISSUE TITLE
Baking Material ID leads to crash

### ISSUE THREAD

**Issue by Sayayaya** [franMarz/TexTools-Blender#75]
Blender 2.91.0

When clicking bake material ID after assigning 

Getting 

![image](https://user-images.githubusercontent.com/18683155/112720760-5a1fd000-8ef8-11eb-8249-692211df1110.png)

**Comment by franMarz** [comment]
Not happening in my end in Blender 2.91 with the latest version of TexTools. Are you using the latest version from here?:
[https://github.com/SavMartin/TexTools-Blender/releases/download/v1.4.2/TexTools_1_4_2.zip](https://github.com/SavMartin/TexTools-Blender/releases/download/v1.4.2/TexTools_1_4_2.zip)
Please add a comment with the exact steps needed to reproduce the error, in text or with a video/gif (prefereable). And share with us the .blend file where this happens if possible.

**Comment by franMarz** [comment]
Please note that the maximum number of materials present in the scene must be 256 to use material ID baking. This is the only current limitation that can explain your error.
