### ISSUE TITLE
Different island size of identical mesh parts

### ISSUE THREAD

**Issue by Rayzorblade23** [franMarz/TexTools-Blender#91]
I am trying to rectify the mesh of a symmetrical object. The two mesh parts below are exactly the same shape after unwrapping. When applying Rectify they're stretched very differently.

After Unwrapping:
![image](https://user-images.githubusercontent.com/41338248/123550140-7425b480-d76c-11eb-89f9-6a2e470d7f9b.png)

After Rectify:
![image](https://user-images.githubusercontent.com/41338248/123550161-97506400-d76c-11eb-849a-1f7f52792a94.png)

**Comment by franMarz** [comment]
This is related to the Rectify code, based on the UV Squares addon. If the author of that addon improves its code, we'll upgrade the Rectify module. Otherwise, most likely Rectify will remain behaving the same. The only thing I can point out is: the outcome of the script relies on the active face selected a lot. So, if you run Rectify for each island separately, and the active face you choose for each one is symmetrical respect the other, maybe you get the same result. Maybe.

**Comment by Rayzorblade23** [comment]
> This is related to the Rectify code, based on the UV Squares addon. If the author of that addon improves its code, we'll upgrade the Rectify module. Otherwise, most likely Rectify will remain behaving the same. The only thing I can point out is: the outcome of the script relies on the active face selected a lot. So, if you run Rectify for each island separately, and the active face you choose for each one is symmetrical respect the other, maybe you get the same result. Maybe.

Thank you so much for you quick response. While it's too bad the issue might not be fixed any time soon, your advice regarding the active face appears to working very well. Thanks!
